# Site
name: "Ankit's Blog"
title: "Ankit's Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
domain_name: 'https://ankitjain28.me'
google_analytics: 'UA-116986205-1'
resume: "https://drive.google.com/file/d/1TTlGmy89KNEzf2BltE8zdp74-5wAn3ga/view"
disqus: 'ankitjain28'
# mailchimp-list: 
include: ["_pages"]
permalink: /:title/
related_post: "enabled"
# Authors
authors:
  ankit:
    name: "Ankit Jain"
    display_name: "Ankit Jain"
    avatar: 'assets/images/ankit.jpg'
    email: ankitjain28may77@gmail.com
    web: "https://ankitjain28.me"
    twitter: https://twitter.com/ankitjain28may
    description: "DevOps Engineer @Razorpay | CommunityBridge Mentee @Keptn | @Drupal GSoC Alum | #GitHubCampusExpert Alum | GCI & GSoC'19 Mentor @Drupal | Speaker | Writer"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-minifier
  - jekyll-gzip
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

# picture plugin
picture:
  ignore_missing_images: true
  fast_build: true
  suppress_warnings: true


kramdown:
  input: GFM
  syntax_highlighter: rouge

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-3543986660328516"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

sass:
  style: compressed


jekyll-minifier:
  uglifier_args:
    harmony: true