version: '3'

networks:
  internal:
  external:

volumes:
  certbot-etc:

services:
  mysql:
    build:
      context: ./docker/mariadb/
      dockerfile: Dockerfile
    image: blog-db
    container_name: blog-db
    volumes:
      - ${DB_PATH}:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      DB_PATH: '${DB_PATH}'
    networks:
      - internal
    restart: always

  drupal:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    image: blog-drupal
    container_name: blog
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_HOSTNAME: '${MYSQL_HOSTNAME}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PORT: '${MYSQL_PORT}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    depends_on: 
      - mysql
    networks:
      - internal
      - external
    restart: always

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: blog-nginx
    container_name: blog-webserver
    ports:
      - "${APP_PORT}:80"
      - "443:443"
    environment:
      APP_PORT: '${APP_PORT}'
    volumes:
      # - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/drupal-ssl.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - drupal
    networks:
      - external
    restart: always

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: blog-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - .:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html/drupal/web --email ankitjain28may77@gmail.com --agree-tos --no-eff-email --force-renewal -d ankitjain28.xyz -d www.ankitjain28.xyz