version: '2'
services:
  drupaldb:
    build: ./docker/mariadb/
    image: drupal-mariadb
    container_name: drupaldb
    volumes:
      - ${DB_PATH}:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      DB_PATH: '${DB_PATH}'
    networks:
      - drupal
    restart: always
  drupal:
    build: ./docker/php/
    image: "drupal-php"
    container_name: drupal-app
    volumes:
      - .:/var/www/html
      # - drupal-sync:/var/www/html:nocopy
    links:
      - "drupaldb:mysql"
    networks:
      - drupal
    restart: always
  nginx:
    build: ./docker/nginx
    image: drupal-nginx
    container_name: drupal-webserver
    ports:
      - "${APP_PORT}:80"
      # - "8028:22"
    environment:
      APP_PORT: '${APP_PORT}'
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
      # - drupal-sync:/var/www/html:nocopy
    links:
      - "drupaldb:mysql"
      - "drupal:php"
    networks:
      - drupal
    restart: always

volumes:
  drupal-sync:
    external: true
networks:
  drupal:
