---

- name: Checking for backup - {{backup_dir}}/{{backup_folder_name}}
  stat:
    path: "{{backup_dir}}/{{backup_folder_name}}"
  register: backup_stat

- name: Moving {{project_dir}}/{{project_folder_name}} to {{backup_dir}}/{{backup_folder_name}}-old
  command: mv {{project_dir}}/{{project_folder_name}}
    {{backup_dir}}/{{backup_folder_name}}-old
  when: backup_stat.stat.exists

- name: Moving {{backup_dir}}/{{backup_folder_name}} to {{project_dir}}/{{project_folder_name}}
  command: mv {{backup_dir}}/{{backup_folder_name}}
    {{project_dir}}/{{project_folder_name}}
  when: backup_stat.stat.exists

- name: Moving {{backup_dir}}/{{backup_folder_name}}-old to {{backup_dir}}/{{backup_folder_name}}
  command: mv {{backup_dir}}/{{backup_folder_name}}-old
    {{backup_dir}}/{{backup_folder_name}}
  when: backup_stat.stat.exists


