---

- name: Giving www-data permission to sites
  command: docker exec drupal /bin/sh -c "cd web && chown -R www-data:www-data sites/"

- name: Importing Configuration
  command: docker exec drupal composer drupal ci

- name: Rebuilding Cache
  command: docker exec drupal composer drupal cr
